 # Spring db properties
spring:
  data:
    mongodb:
      uri: mongodb+srv://monse:monse@cluster0.mb8zbcw.mongodb.net/CONSULTA_YA?retryWrites=true&w=majority
# HTTP Server
server:
  port: 8081
  servlet:
     contextPath: /auth